### ISSUE TITLE
Is it recommended to install this extension by cloning this repo?

### ISSUE THREAD

**Issue by curusarn** [sustmi/gnome-shell-extension-windowoverlay-icons#14]
I tried to clone this repository to `~/.local/share/gnome-shell/extensions/windowoverlay-icons@sustmidown.centrum.cz` and it did show up in the gnome tweak tools.

However, it did not work when I tried to enable it.

Do I need to build the extension after I clone it? If so, then how?

Thanks

Simon

**Comment by curusarn** [comment]
Running `make all` built the extension and it works now.

Is it recommended to install the extension this way?
I want to avoid installing and updating all my extensions through the `extension.gnome.org` site.

**Comment by sustmi** [comment]
Hello @curusarn . Sorry for the late reply.

I guess that the recommended way is either to use `extension.gnome.org` or if you use Fedora, you can install the extension using the [`gnome-shell-extension-windowoverlay-icons` package](https://rpmfind.net/linux/rpm2html/search.php?query=gnome-shell-extension-windowoverlay-icons&submit=Search+...).

However, the `git clone` to `~/.local/share/gnome-shell/extensions/windowoverlay-icons@sustmidown.centrum.cz` and `make all` should work too because `make all` is actually run in `make zip` target that I use to release new version.
