### ISSUE TITLE
Doesn't work with gnome 3.38

### ISSUE THREAD

**Issue by mohegan** [sustmi/gnome-shell-extension-windowoverlay-icons#18]
The extension doesn't work with gnome 3.38 :

`sept. 17 21:36:09 jack-XPS-L322X gnome-shell[906]: JS ERROR: Extension windowoverlay-icons@sustmidown.centrum.cz: TypeError: class heritage originalWindowOverlay is not an object or null
                                                   enable@/home/jack/.local/share/gnome-shell/extensions/windowoverlay-icons@sustmidown.centrum.cz/extension.js:49:31
                                                   _callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:168:32
                                                   loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:349:26
                                                   _loadExtensions/<@resource:///org/gnome/shell/ui/extensionSystem.js:595:18
                                                   collectFromDatadirs@resource:///org/gnome/shell/misc/fileUtils.js:27:28
                                                   _loadExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:570:19
                                                   _enableAllExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:604:18
                                                   _sessionUpdated@resource:///org/gnome/shell/ui/extensionSystem.js:635:18
                                                   init@resource:///org/gnome/shell/ui/extensionSystem.js:57:14
                                                   _initializeUI@resource:///org/gnome/shell/ui/main.js:272:22
                                                   start@resource:///org/gnome/shell/ui/main.js:162:5
                                                   @<main>:1:47
`

**Comment by cbomgit** [comment]
The WindowOverlay class was removed and merged into WindowClone, so it might take a bit of a refactor to fix this.

https://github.com/GNOME/gnome-shell/commit/c5634335b

https://gitlab.gnome.org/GNOME/gnome-shell/-/merge_requests/1298

I don't have any experience working with gnome shell but I like this extension so I dug into what might have broken this. Hopefully this is helpful for somebody with more experience.

**Comment by somepaulo** [comment]
The extension hasn't been updated in over two years, and the dev isn't responding. Is there anyone out there with the skills and knowledge to fix/fork it with GS 3.38 support?

**Comment by sustmi** [comment]
Sorry, I don't have much time to maintain this extension lately. When it breaks on my machine, it's a priority for me because I use it, but since Fedora 32 still uses GNOME Shell 3.36, I do not have much motivation to make it work in 3.38.
I will see if I will be able to upgrade to the GNOME Shell 3.38 from Fedora Rawhide. Only then I could try to fix it.

Thanks to @cbomgit for pointing out the changes in the API.

Anyway, I already wanted to rewrite the extension to use `WindowClone` instead of `WindowOverlay` because of issue https://github.com/sustmi/gnome-shell-extension-windowoverlay-icons/issues/13 , but it was not worth doing it just to fix animation. Now it's inevitable.

**Comment by smichel17** [comment]
@sustmi I also run F32 and, like @somepaulo, like this extension quite a lot but am not familiar with gnome internals. Basically:

- I'd be willing to spend a few (2-3) werkends working on this.

- If I had to start from zero, most of that time would probably be spent understanding existing code in gnome-shell. Not worth it.

- If I knew in advance which parts of gnome-shell I [didn't] need to understand & had a rough idea of how the implementation should work, I could make useful progress.

So, if you (or someone else) were to write an explanation of how you'd implement it, or a partial/buggy implementation, I'd be willing to help finish it.

**Comment by nariox** [comment]
Hi @smichel17, there are two things that need to be changed. First, tweener has been removed from mutter. You can simply import tweener differently [(like here)](https://github.com/Fmstrat/wintile/commit/d7d4e7a84a1535cbd08be8d7108011cedc0b5b01) or replace with the native clutter animations [(like here)](https://github.com/codito/gnome-pomodoro/pull/517/files) (although my implementation didn't fully work, I'm a noob, so I can give no help there).

The second part come from the MR that @cbomgit posted. G-S used to have two classes, windowclone (which is the little image you see when you go on overview) and windowoverlay (which overlayed over the windowclone). This extension was using overlay, but would need to move to using clone.

What you would need to do is modify the extension.js to extend the windowclone class so that it overlays the icon over the original windowclone. If you look for how G-S does the close button overlay [(here)](https://gitlab.gnome.org/GNOME/gnome-shell/-/blob/master/js/ui/windowPreview.js). But I have 0 experience with JS, so I am quite limited by what I can do, otherwise I would try to help more.

One shortcut that I thought would be possible would be to copy the windownavigator extension approach, which is an "official" extension, but somehow it has not yet been updated to work with 3.38 [(as seen here)](https://gitlab.gnome.org/GNOME/gnome-shell-extensions/-/issues/259). If enough people chime here, we might be able to get a commit we can study to fix this extension.

**Comment by nariox** [comment]
By the way, the commit that moved the overlay to clone is [this one](https://gitlab.gnome.org/GNOME/gnome-shell/-/merge_requests/1298/diffs?commit_id=280abb8a6da533d5ef8e4ba4c7c240613b4d6e4f)

**Comment by sustmi** [comment]
I just released v36 of this extension (in review on https://extensions.gnome.org) that supports GNOME Shell v3.38.

@nariox: Thank you for the breakdown. I actually managed to implement the extensions by extending `WindowPreview` (not `WindowClone` as I and you suggested).

**Comment by sustmi** [comment]
@smichel17: Thank you for your willingness to help. I do not think I can explain what parts of GNOME Shell code you need to understand so that you can write GNOME Shell extensions.
At least, I will try to give you few tips:
- Clone the [GNOME Shell repository](https://gitlab.gnome.org/GNOME/gnome-shell/) and use some IDE that help you search in the code - you will need it a lot.
- Use Looking Glass tool to inspect the UI and try to find what component you need to modify by your extension. You can run it from the Run Command popup (`ALT+F2`) by entering `lg` command.
- Find the code of the component in the GNOME Shell repository and try to find the part that you want to modify.
- Get familiar with different code modification techniques (like monkey-patching).
- Find some simple extensions (like [launch-new-instance](https://gitlab.gnome.org/GNOME/gnome-shell-extensions/-/tree/master/extensions/launch-new-instance) and try to learn by example how extensions are written.
- When I need to use some class from `imports.gi.St` namespace (like `St.Icon`), I use this documentation https://developer.gnome.org/st/stable/pt01.html . However, as the documentation is for C++, you must learn how the JavaScript binding works. For example `st_icon_get_icon_size()` function is called like this `icon.icon_size` in JavaScript.
- Also, you might find useful if you [learn about Signals](https://developer.gnome.org/gnome-devel-demos/stable/03_getting_the_signal.js.html.en) which are basically an implementation of event listener / observer design pattern.

**EDIT:** I found this wiki page https://wiki.gnome.org/Projects/GnomeShell/Extensions/Writing which looks like quite comprehensive guide to writing GNOME Shell extensions. I also links to [documentation of the *St* library that is written in JavaScript](https://gjs-docs.gnome.org/st10~1.0_api/).

If you want to understand this specific extension:
- it extends [`WindowPreview`](https://gitlab.gnome.org/GNOME/gnome-shell/-/blob/master/js/ui/windowPreview.js) class (specifically `_init`, `showOverlay`, `hideOverlay` and `_onDestroy` methods)
- it inserts [`St.Bin`](https://gjs-docs.gnome.org/st10~1.0_api/st.bin) widget inside the window preview
- this widget serves as a background for another widget [`St.Icon`](https://gjs-docs.gnome.org/st10~1.0_api-icon/)
- the app icon is fetched using [`Shell.App.create_icon_texture()`](https://gjs-docs.gnome.org/shell01~0.1_api/shell.app#method-create_icon_texture) method

**Comment by nariox** [comment]
@sustmi : awesome! Thank you very much. This was one of the few "must-have" extensions missing for me on G-S 3.38.

**Comment by mohegan** [comment]
Thanks @sustmi ! It works for me.
You just have forgotten the version number in the **medata.json**. I have modified the file like this :
```
{
    "shell-version": ["3.38"],
    "uuid": "windowoverlay-icons@sustmidown.centrum.cz",
    "name": "WindowOverlay Icons",
    "description": "Add application icons to window overview",
    "url": "https://github.com/sustmi/gnome-shell-extension-windowoverlay-icons",
    "settings-schema": "org.gnome.shell.extensions.windowoverlay-icons",
    "gettext-domain": "windowoverlay-icons",
    "version": 36
}
```

I think you can push it to extensions.gnome.org repository !

**Comment by sustmi** [comment]
> You just have forgotten the version number in the medata.json

I am not sure if it has any value to add the version there. Is there any code that reads this version number?
I bet I would forget to update it at some point in the future so I better not add it at all. :)

**Comment by mohegan** [comment]
If the metadata.json doesn't have the version line, the version from gnome shell extension website has the priority !
So, I have a message from Gnome Shell Extension to tell me there is an update available and in the website ([https://extensions.gnome.org/extension/302/windowoverlay-icons/](https://extensions.gnome.org/extension/302/windowoverlay-icons/), I can update the extension :
![Capture d’écran de 2020-11-01 02-16-14](https://user-images.githubusercontent.com/635456/97793181-d54eb580-1be8-11eb-8a69-898e288ceea4.png)

**Comment by mohegan** [comment]
But, when you put an update in the gnome shell extension, the version line is added automatically.
After the update, the metadata.json is modified :
```
{
  "_generated": "Generated by SweetTooth, do not edit",
  "description": "Add application icons to window overview",
  "gettext-domain": "windowoverlay-icons",
  "name": "WindowOverlay Icons",
  "settings-schema": "org.gnome.shell.extensions.windowoverlay-icons",
  "shell-version": [
    "3.38"
  ],
  "url": "https://github.com/sustmi/gnome-shell-extension-windowoverlay-icons",
  "uuid": "windowoverlay-icons@sustmidown.centrum.cz",
  "version": 36
}
```
I think you can add the version line in your github repository. So, the repository will have the priority in future updates.

What do you think about this ?

**Comment by sustmi** [comment]
> But, when you put an update in the gnome shell extension website, the version line is added automatically.

Oh, you are right. Actually, it is convenient for me to let the extensions website do it for me. I really do not need the version in the file itself. The version in the Git repository is denoted by the tags: https://github.com/sustmi/gnome-shell-extension-windowoverlay-icons/tags .

My flow goes like this:
1. I make changes needed
2. I test them
3. I run `make zip` to create the `.zip`
4. I upload it to the extensions.gnome.org website
5. It gives me a new version number (one higher than the previous) and I mark the commit that the ZIP was created from with appropriate Git tag.

If I added the version in the `metadata.json`, it would be one extra step for me.

Also, if the reviewer on extensions.gnome.org asks for some changes, I will just submit the updated version with new version number so that it is clear what changes were done.

Is there any advantage that you see in adding the version in `metadata.json`?

**Comment by sustmi** [comment]
> If the metadata.json doesn't have the version line, the version from gnome shell extension website has the priority !

Oh, sorry, I missed your previous message. Now, it makes sense to me. OK, I will add version number in one of my next releases so that you don't get extra update notifications.

**Comment by mohegan** [comment]
Thanks !
