### ISSUE TITLE
Journal spammed with `Can't update stage views actor * is on because it needs an allocation.` when opening the overview

### ISSUE THREAD

**Issue by BjoernDaase** [sustmi/gnome-shell-extension-windowoverlay-icons#19]
* Fedora 33
* Gnome-shell 3.38.1

When opening the overview with the extension enabled you always get the following trace in your logs
```
Nov 06 08:12:36 xps-9370 gnome-shell[3808]: Can't update stage views actor overviewGroup is on because it needs an allocation.
Nov 06 08:12:36 xps-9370 gnome-shell[3808]: Can't update stage views actor Gjs_ui_workspacesView_WorkspacesView is on because it needs an allocation.
Nov 06 08:12:36 xps-9370 gnome-shell[3808]: Can't update stage views actor Gjs_ui_workspace_Workspace is on because it needs an allocation.
Nov 06 08:12:36 xps-9370 gnome-shell[3808]: Can't update stage views actor Gjs_ui_windowPreview_WindowPreview is on because it needs an allocation.
Nov 06 08:12:36 xps-9370 gnome-shell[3808]: Can't update stage views actor StBin is on because it needs an allocation.
Nov 06 08:12:36 xps-9370 gnome-shell[3808]: Can't update stage views actor StIcon is on because it needs an allocation.
Nov 06 08:12:36 xps-9370 gnome-shell[3808]: Can't update stage views actor ClutterActor is on because it needs an allocation.
Nov 06 08:12:36 xps-9370 gnome-shell[3808]: Can't update stage views actor Gjs_ui_windowPreview_WindowPreview is on because it needs an allocation.
Nov 06 08:12:36 xps-9370 gnome-shell[3808]: Can't update stage views actor StBin is on because it needs an allocation.
Nov 06 08:12:36 xps-9370 gnome-shell[3808]: Can't update stage views actor StIcon is on because it needs an allocation.
Nov 06 08:12:36 xps-9370 gnome-shell[3808]: Can't update stage views actor ClutterActor is on because it needs an allocation.
Nov 06 08:12:36 xps-9370 gnome-shell[3808]: Can't update stage views actor Gjs_ui_windowPreview_WindowPreview is on because it needs an allocation.
Nov 06 08:12:36 xps-9370 gnome-shell[3808]: Can't update stage views actor StBin is on because it needs an allocation.
Nov 06 08:12:36 xps-9370 gnome-shell[3808]: Can't update stage views actor StIcon is on because it needs an allocation.
Nov 06 08:12:36 xps-9370 gnome-shell[3808]: Can't update stage views actor ClutterActor is on because it needs an allocation.
Nov 06 08:12:36 xps-9370 gnome-shell[3808]: Can't update stage views actor Gjs_ui_windowPreview_WindowPreview is on because it needs an allocation.
Nov 06 08:12:36 xps-9370 gnome-shell[3808]: Can't update stage views actor StBin is on because it needs an allocation.
Nov 06 08:12:36 xps-9370 gnome-shell[3808]: Can't update stage views actor StIcon is on because it needs an allocation.
Nov 06 08:12:36 xps-9370 gnome-shell[3808]: Can't update stage views actor ClutterActor is on because it needs an allocation.
Nov 06 08:12:36 xps-9370 gnome-shell[3808]: Can't update stage views actor Gjs_ui_windowPreview_WindowPreview is on because it needs an allocation.
Nov 06 08:12:36 xps-9370 gnome-shell[3808]: Can't update stage views actor StBin is on because it needs an allocation.
Nov 06 08:12:36 xps-9370 gnome-shell[3808]: Can't update stage views actor StIcon is on because it needs an allocation.
Nov 06 08:12:36 xps-9370 gnome-shell[3808]: Can't update stage views actor ClutterActor is on because it needs an allocation.
Nov 06 08:12:36 xps-9370 gnome-shell[3808]: Can't update stage views actor Gjs_ui_windowPreview_WindowPreview is on because it needs an allocation.
Nov 06 08:12:36 xps-9370 gnome-shell[3808]: Can't update stage views actor StBin is on because it needs an allocation.
Nov 06 08:12:36 xps-9370 gnome-shell[3808]: Can't update stage views actor StIcon is on because it needs an allocation.
Nov 06 08:12:36 xps-9370 gnome-shell[3808]: Can't update stage views actor ClutterActor is on because it needs an allocation.
```

This looks super similar to https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/3098, which happens in other situations but with the same logs. It also has a pending MR, so maybe you are able to adapt their solution.

**Comment by sustmi** [comment]
Thank you for reporting. 
I did not find any problem in the code of this extension. I guess that the problem is really in GNOME Shell itself.
I will wait for the release of the mentioned merge request (https://gitlab.gnome.org/GNOME/gnome-shell/-/merge_requests/1481) to see if it helps.

**Comment by BjoernDaase** [comment]
Unfortunately, that does not fix the problem of the extension. I am running https://copr.fedorainfracloud.org/coprs/pp3345/gnome-with-patches/, which includes the MR, but the problem persists.

**Comment by sustmi** [comment]
Thank you for testing that. Unfortunately, I have no clue what to do with this.
I do not know what the error message exactly means and what should I do with that. 
I cannot even find the code that prints the message so that I could try to understand it from the context:
- https://github.com/search?q=%22Can%27t+update+stage+views%22&type=Code
- https://gitlab.gnome.org/search?group_id=8&project_id=547&repository_ref=&scope=blobs&search=%22Can%27t+update+stage+views%22&snippets=false

**Comment by BjoernDaase** [comment]
> Thank you for testing that. Unfortunately, I have no clue what to do with this.
> I do not know what the error message exactly means and what should I do with that.
> I cannot even find the code that prints the message so that I could try to understand it from the context:
> 
> * https://github.com/search?q=%22Can%27t+update+stage+views%22&type=Code
> * https://gitlab.gnome.org/search?group_id=8&project_id=547&repository_ref=&scope=blobs&search=%22Can%27t+update+stage+views%22&snippets=false

Asking on discourse.gnome.org might be a good idea.

**Comment by BjoernDaase** [comment]
Btw, [here](https://gitlab.gnome.org/GNOME/mutter/-/blob/master/clutter/clutter/clutter-actor.c#L15758) is where the error message comes from.

**Comment by sustmi** [comment]
Thank you so much @BjoernDaase !

It looks like the Gitlab search is not perfect because it [does not find the "Can't update stage views actor" string](https://gitlab.gnome.org/search?utf8=%E2%9C%93&search=%22Can%27t+update+stage+views+actor%22&group_id=8&project_id=547&scope=&search_code=true&snippets=false&repository_ref=master&nav_source=navbar) and the [GitHub mirror](https://github.com/GNOME/clutter/blob/master/clutter/clutter-actor.c) is broken because the last commit in https://github.com/GNOME/clutter/blob/master/clutter/clutter-actor.c is on 7 Oct 2019 (not 23 Oct 2020 like on Giltab).
That's why I could not find it.

**Comment by BjoernDaase** [comment]
The good thing is that with https://gitlab.gnome.org/GNOME/gnome-shell/-/merge_requests/1605 this is baked into GNOME 40 🎉

**Comment by sustmi** [comment]
I think finally managed to find the cause of "Can't update stage views actor ... is on because it needs an allocation." warning messages. It was fixed in v37: https://github.com/sustmi/gnome-shell-extension-windowoverlay-icons/releases/tag/v37 .
Could you, please, confirm that it helped on your system too, @BjoernDaase ?

Also, thanks for letting me know that GNOME Shell will have native application icons. It's a strange feeling that they are finally (after almost 10 years) adding a feature without which I could not stand using GNOME Shell.

**Comment by BjoernDaase** [comment]
@sustmi I actually can't tell because I am using the GNOME 40 copr right now, so for me there is no need for your extension anymore.

But if it's fixed for you I think we can safely close this issue.
