### ISSUE TITLE
Extension breaks overlay view after minimizing a window

### ISSUE THREAD

**Issue by DarwinAwardWinner** [sustmi/gnome-shell-extension-windowoverlay-icons#22]
If this extension is enabled *and* the last window management action was to minimize a window, then the overlay view breaks when activated. It seems to play only one or maybe a few frames of the "present windows" animation and then freeze and become unresponsive. Only pressing the super key again exits this otherwise non-functional overlay view. The overlay view doesn't regain functionality until you switch windows or un-minimize the windows that was minimized.

**Comment by sustmi** [comment]
I have a suspicion that this behavior is caused by the same issue as: https://github.com/sustmi/gnome-shell-extension-windowoverlay-icons/issues/20 .

Can you please try a new version (v37): https://github.com/sustmi/gnome-shell-extension-windowoverlay-icons/releases/tag/v37 and let me know whether the animation still gets stuck on your system?

**Comment by DarwinAwardWinner** [comment]
I'm not sure which version I have installed, but after installing the latest from extensions.gnome.org, this seems to be fixed.

**Comment by sustmi** [comment]
Then you have the fixed version. Thank you for letting me know.
