### ISSUE TITLE
Question: Can I use title instead of icon?

### ISSUE THREAD

**Issue by nlpsuge** [sustmi/gnome-shell-extension-windowoverlay-icons#8]
Can I use title instead of icon? It's very useful when you open many windows of the same application.

I found this issue: https://bugzilla.gnome.org/show_bug.cgi?id=783953 

Is it possible to add title on the bottom of every window in the overview?

**Comment by sustmi** [comment]
Hi @nlpsuge .

I can see that you already created a separate extension for this: https://github.com/nlpsuge/Always-Show-Titles-In-Overview/ . Nice work! :+1: 
That was the first idea that came to my mind - that it should be a separate extension since it does not have anything in common with application icons.

However, I can see that in your extension you rewrite the original methods of `WindowOverlay` class:
https://github.com/nlpsuge/Always-Show-Titles-In-Overview/blob/master/extension.js#L74 .
I tried your extension and I can see that it is partly incompatible with my gnome-shell-extension-windowoverlay-icons.

If you want to make the extensions compatible, you should only "inject" your code before or after the existing one.
I guess that the only thing you need for the "Always Show Titles In Overview" extension it to inject code after `_animateInvisible` method that would stop the tween (animation) of hiding the title and set the opacity back to `255` instead.

I quickly tried to change your extension to only do this in `enable()` method and it worked:
```js
windowOverlayInjections['hideCloseButton'] = injectToFunction(Workspace.WindowOverlay.prototype, 'hideCloseButton', function () {
        this.title.show();
    });

    windowOverlayInjections['_animateVisible'] = injectToFunction(Workspace.WindowOverlay.prototype, '_animateVisible', function () {
        Tweener.removeTweens(this.title);
        this.title.opacity = 255;
    });

    windowOverlayInjections['_animateInvisible'] = injectToFunction(Workspace.WindowOverlay.prototype, '_animateInvisible', function () {
        Tweener.removeTweens(this.title);
        this.title.opacity = 255;
    });
    
    windowOverlayInjections['show'] = injectToFunction(Workspace.WindowOverlay.prototype, 'show', function () {
        this.title.show();
    });

    windowOverlayInjections['hide'] = injectToFunction(Workspace.WindowOverlay.prototype, 'hide', function () {
        this.title.hide();
    });
```

Note that I still run GNOME Shell v3.30.2. In v3.32 the `hideCloseButton()` method no longer exists but it looks like `hideOverlay()` took it's place in hiding the title. It may or may not be necessary to call `this.title.show()` after the original `hideOverlay()` code.

Now, that there is a separate extension for this, I close this issue.

**Comment by nlpsuge** [comment]
Thanks for your advice, I'll try your idea in my spare time.

Thanks again.
